name: kashou
description: Music player with local library playback and YouTube streaming
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.10
  audio_service: ^0.18.12
  audio_session: ^0.2.2
  
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  file_picker: ^10.3.3
  
  sqflite: ^2.3.0
  
  audiotags: ^1.4.2
  # on_audio_query: ^3.0.0-beta.0
  
  provider: ^6.1.1
  get_it: ^8.2.0
  
  google_fonts: ^8.2.0
  dynamic_color: ^1.7.0
  flutter_colorpicker: ^1.0.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  package_info_plus: ^9.0.0
  image: ^4.0.17
  http: ^1.2.1
  youtube_explode_dart: ^3.0.2
  innertube_dart:
    path: packages/innertube_dart
  share_plus: ^7.2.2
  url_launcher: ^6.3.0
  
  flutter_chrome_cast: ^1.2.5
  
  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  flutter_inappwebview: ^6.1.5
  material3_expressive_loading_indicator: ^0.1.2
  material_new_shapes: ^1.0.0

dependency_overrides:
  just_audio:
    git:
      url: https://github.com/primalkz/just_audio.git
      ref: hires
      path: just_audio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/potoken/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#1F2227"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"

flutter_native_splash:
  color: "#fcf5fb"
  image: assets/images/splash_native.png
  color_dark: "#111014"
  image_dark: assets/images/splash_native_dark.png
  android: true
  ios: false
  android_12:
    image: assets/images/splash_native.png
    color: "#fcf5fb"
    image_dark: assets/images/splash_native_dark.png
    color_dark: "#111014"